### ISSUE TITLE
usb.core.USBError Errno 75 Overflow 

### ISSUE THREAD

**Issue by Mizuki-ENG** [virtualabs/cc2531-killerbee-fw#10]
Occured when using zbwireshark to capture the zigbee unlock door packet command as below 
pyusb version 1.0.1
cc2531 firmware 2.1r1
Any help ,Suggestion ?

Thank you.

└─$ sudo zbwireshark -c 25        
\Auto-detection is being deprecated - Please specify hardware
Warning: You are using pyUSB 1.x, support is in beta.
zbwireshark: listening on 'CC2531 USB Dongle', channel 25, page 0 (2475.0 MHz), link-type DLT_IEEE802_15_4, capture size 127 bytes
Error args: (75, 'Overflow')
Traceback (most recent call last):
  File "/usr/local/bin/zbwireshark", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==3.0.0b2', 'zbwireshark')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/EGG-INFO/scripts/zbwireshark", line 108, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/EGG-INFO/scripts/zbwireshark", line 84, in main
    packet = kb.pnext()
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/killerbee/__init__.py", line 442, in pnext
    return self.driver.pnext(timeout)
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/killerbee/dev_bumblebee.py", line 400, in pnext
    self.process_rx()
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/killerbee/dev_bumblebee.py", line 156, in process_rx
    raise e
  File "/usr/local/lib/python3.10/dist-packages/killerbee-3.0.0b2-py3.10-linux-x86_64.egg/killerbee/dev_bumblebee.py", line 149, in process_rx
    nbytes = self.dev.read(Bumblebee.EP_IN, self.usb_rx_buffer, 10)
  File "/usr/local/lib/python3.10/dist-packages/usb/core.py", line 983, in read
    ret = fn(
  File "/usr/local/lib/python3.10/dist-packages/usb/backend/libusb1.py", line 828, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/local/lib/python3.10/dist-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/local/lib/python3.10/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow

**Comment by LordofMisery** [comment]
Trying the python 2
ps **bumblebee doesn't support cc2531 anymore .**

**Comment by jbasement** [comment]
Hm not sure about why your command fails, but you can also try using _zbdump_. That's what I use to capture packets and then afterwards open them in wireshark. 

Oh and I just took a look at the zbwireshark tool. It tries starting wireshark via cli first. Are you sure wireshark is installed on your device? Are you able to execute *wireshark* on your terminal to open it?

@LordofMisery where do you get that information from? The latest firmware is even named cc2531? For me it works fine on a Ti cc2531 from Amazon

**Comment by virtualabs** [comment]
Unfortunately, this is a known bug of this firmware, sometimes it triggers this kind of error on libusb because I think I'm doing it wrong at some point in the code. The more Zigbee devices in the area the more often it happens, other contributors reported.

**Comment by oldoperator78** [comment]
This is true but at least it gets me to be able to use the cheap cc2531 off amazon, and I can do most of it. The libusb errors happen when using stumbler most for me.
