### ISSUE TITLE
0 packet captured

### ISSUE THREAD

**Issue by Mathil2Net** [virtualabs/cc2531-killerbee-fw#5]
Thanks for this project!
I use a TI CC2531 to listen and decypher frames in ZigBee Pro and Green Power. However, since the last few weeks my dongle does not "hear" those frames and when I launch zbdump 0 packet is captured. I checked with another dongle and wireshark and I am sure there are some frames coming.
No error is raised by killerbee, so I think it comes from BumbleBee and its implementation inside KillerBee. After seeing your answer to my comment on your website I am waiting for the new version !

Thanks again for your work!

**Comment by MikeColeGuru** [comment]
I am also not getting any packets with zbdump.   The lights on the CC2531 dongle are flashing like it is getting packets.  

I flashed the BumbleBee 2.1 hex and I'm using the develop branch of https://github.com/virtualabs/killerbee
I am also using Ubuntu 20.04 and Python 3.8.10

```
$ sudo zbdump -i 8:28 -c 15 -w cap1.cap
Autodetection features will be deprecated - please include device string (e.g. -d apimote)
Auto-detection is being deprecated - Please specify hardware
Warning: You are using pyUSB 1.x, support is in beta.
zbdump: listening on '8:28', channel 15, page 0 (2425.0 MHz), link-type DLT_IEEE802_15_4, capture size 127 bytes
```

I am not certain what I am doing wrong.

**Comment by MikeColeGuru** [comment]
I figured something out.

It was defaulting to the cc253x driver and not bumblebee device.

So, I specified it to use bumblebee and have a new error

```
$ sudo zbdump -i 8:30 -d bumblebee -c 15 -w cap1.cap
Warning: You are using pyUSB 1.x, support is in beta.
Traceback (most recent call last):
  File "/usr/local/bin/zbdump", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==3.0.0b2', 'zbdump')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/zbdump", line 159, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/zbdump", line 135, in main
    kb = KillerBee(device=args.devstring, hardware=args.device)
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/killerbee/__init__.py", line 96, in __init__
    self.driver = Bumblebee(device, self.__bus)
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/killerbee/dev_bumblebee.py", line 91, in __init__
    self.dev.set_configuration()
AttributeError: 'str' object has no attribute 'set_configuration'
```

**Comment by Mathil2Net** [comment]
Hi,
what is "-d bumblebee" for ?

**Comment by MikeColeGuru** [comment]
> what is "-d bumblebee" for ?

There are a number of device drivers built into killerbee.  By default it tries to autodetect but you can choose which one you want to use.

If you look in the source https://github.com/virtualabs/killerbee/tree/develop/killerbee

```
dev_apimote.py
dev_cc253x.py
dev_rzusbstick.py
dev_sl_beehive.py
dev_telosb.py
dev_zigduino.py
dev_bumblebee.py
dev_freakduino.py
dev_sewio.py
dev_sl_nodetest.py
dev_template.py
```

**Comment by Mathil2Net** [comment]
Okay thanks, I don't need it, killerbee seems to find it by itself.
I do not have any issue when I try "sudo zbdump -i 8:30 -d bumblebee -c 15 -w cap1.cap" so I cannot help you on that sorry

**Comment by MikeColeGuru** [comment]
> I do not have any issue

Does it capture packets?

**Comment by Mathil2Net** [comment]
Yes but not everytime. I have another dongle to sniff packets, and sometimes bumblebee dongle does not catch any packet whereas the other one does. But on virtualabs website it was said that it needed an update to correct this issue. For now the new version is not compatible with every version of killerbee so I am still waiting.

**Comment by virtualabs** [comment]
Hello all, I am currently working on it but never had the error @Mathil2Net mentionned. The version 2.1 hex release has introduced other bugs a new release will fix, sorry for the inconvenience.  I'll push everything into the repos and let you know when the new version is available ! (Doing my best to fix this as soon as possible ...)

**Comment by Mathil2Net** [comment]
Thanks! No problem, I'm not in a hurry

**Comment by virtualabs** [comment]
I released version 2.1r1 yesterday, and so far it seems to cause some USB overflow errors (see issue #7). This version was supposed to fix multiple bugs, so I guess you should try it and see if it works better with this version. I need to further investigate this USB overflow issue as well. On my side, everything is working fine in a non-dense area with only <10 devices around. I am able to sniff and inject packets, and sometimes I get a timeout error indicating something may be wrong in the firmware. Like I said, need more work on these errors in order to fix them and get the perfect firmware :).

**Comment by remydemy** [comment]
> > I do not have any issue
> 
> Does it capture packets?

@MikeColeGuru Did you ever solve this issue? I seem to have the same problem where no packets are being captured.

**Comment by remydemy** [comment]
Ok nvm if I use version 2.0 and the current develop branch of killerbee zbdump works!
